// Auto-generated Hebrew→English city name mapping
// Source: github.com/eladnava/pikud-haoref-api/cities.json

const cityNames: Record<string, string> = {
  "אבו גוש": "Abu Gosh",
  "אבו סנאן": "Abu Snan",
  "אבו קרינאת": "Abu Qrenat",
  "אבו תלול": "Abu Talul",
  "אבטליון": "Avtalion",
  "אביבים": "Avivim",
  "אביגדור": "Avigdor",
  "אביגיל": "Avigail",
  "אביחיל": "Avihail",
  "אביעזר": "Aviezer",
  "אבירים": "Abirim",
  "אביתר": "Evyatar",
  "אבן יהודה": "Even Yehuda",
  "אבן מנחם": "Even Menachem",
  "אבן ספיר": "Even Sapir",
  "אבן שמואל": "Even Shmuel",
  "אבני איתן": "Avnei Eitan",
  "אבני חפץ": "Avnei Hefetz",
  "אבנת": "Avnat",
  "אבשלום": "Avshalom",
  "אדורה": "Adora",
  "אדורים": "Adoraim",
  "אדמית": "Idmit",
  "אדרת": "Aderet",
  "אודים": "Udim",
  "אודם": "Odem",
  "אום אל קוטוף": "Umm Al-Qutuf",
  "אום בטין": "Umm Batin",
  "אופקים": "Ofakim",
  "אור הגנוז": "Or HaGanuz",
  "אור הנר": "Or HaNer",
  "אור יהודה": "Or Yehuda",
  "אורה": "Ora",
  "אורות": "Orot",
  "אורטל": "Ortal",
  "אורים": "Urim",
  "אורנים": "Oranim",
  "אורנית": "Oranit",
  "אושה": "Usha",
  "אזור": "Azor",
  "אזור תעשייה אלון התבור": "Alon HaTavor Industrial Zone",
  "אזור תעשייה אפק ולב הארץ": "Afek And Lev Ha\"aretz Industrial Zone",
  "אזור תעשייה אריאל": "Ariel Industrial Park",
  "אזור תעשייה באר טוביה": "Be'er Tuvia Industrial Zone",
  "אזור תעשייה בני יהודה": "Bnei Yehuda Industrial Zone",
  "אזור תעשייה בר-לב": "Bar Lev Industrial Zone",
  "אזור תעשייה בראון": "Bar On Industrial Zone",
  "אזור תעשייה ברוש": "Brosh Industrial Zone",
  "אזור תעשייה ברקן": "Barkan Industrial Park",
  "אזור תעשייה גדרה": "Gedera Industrial Area",
  "אזור תעשייה דימונה": "Dimona Industrial Zone",
  "אזור תעשייה הר טוב - צרעה": "Har Tuv - Tzora Industrial Zone",
  "אזור תעשייה חבל מודיעין שוהם": "Hevel Modiin Shoham Industrial Zone",
  "אזור תעשייה יקנעם עילית": "Yokneam Illit Industrial Zone",
  "אזור תעשייה כנות": "Kannot Industrial Zone",
  "אזור תעשייה כפר יונה": "Kfar Yona Industrial Zone",
  "אזור תעשייה כרמיאל": "Carmiel Industrial Zone",
  "אזור תעשייה מבוא כרמל": "Mevo Carmel Industrial Zone",
  "אזור תעשייה מבואות הגלבוע": "Mevuot HaGilboa Industrial Zone",
  "אזור תעשייה מישור אדומים": "Mishor Edomim Industrial Zone",
  "אזור תעשייה מיתרים": "Meitarim Industrial Zone",
  "אזור תעשייה נ.ע.מ": "Noam Industrial Zone",
  "אזור תעשייה ניר עציון": "Nir Etzion Industrial Area",
  "אזור תעשייה נשר - רמלה": "Nesher Industrial Zone (Ramla)",
  "אזור תעשייה עד הלום": "Ad Halom Industrial Zone",
  "אזור תעשייה עידן הנגב": "Idan HaNegev Industrial Zone",
  "אזור תעשייה עמק חפר": "Emek Heffer Industrial Zone",
  "אזור תעשייה צ.ח.ר": "Tzahar Industrial Zone",
  "אזור תעשייה ציפורית": "Tziporit Industrial Zone",
  "אזור תעשייה צפוני אשקלון": "Ashkelon Northern Industrial Zone",
  "אזור תעשייה קדמת גליל": "Kidmat Galil Industrial Zone",
  "אזור תעשייה קיסריה": "Caesarea Industrial Zone",
  "אזור תעשייה קריית ביאליק": "Kiryat Bialik Industrial Zone",
  "אזור תעשייה קריית גת": "Kiryat Gat - Industrial Zone",
  "אזור תעשייה רבדים": "Revadim Industrial Zone",
  "אזור תעשייה רותם": "Rotem Industrial Zone",
  "אזור תעשייה רמת דלתון": "Ramat Dalton Industrial Zone",
  "אזור תעשייה שער בנימין": "Sha'ar Binyamin Industrial Zone",
  "אזור תעשייה שער נעמן": "Sha'ar Na'aman Industrial Zone",
  "אזור תעשייה תימורים": "Timorimg Industrial Zone",
  "אזור תעשייה תרדיון": "Teradion Industrial Zone",
  "אחווה": "Achva",
  "אחוזם": "Ahuzam",
  "אחוזת ברק": "Ahuzat Barak",
  "אחיה": "Achita",
  "אחיהוד": "Achihud",
  "אחיטוב": "Ahituv",
  "אחיסמך": "Ahisemech",
  "אחיעזר": "Achiezer",
  "איבטין": "Ibtin",
  "איבי הנחל": "Ibei HaNahal",
  "איזור תעשייה מילואות צפון": "Milouot Industrial Zone North",
  "אייל": "Eyal",
  "איילת השחר": "Ayelet HaShachar",
  "איירפורט סיטי": "Airport City",
  "אילון": "Eilon",
  "אילניה": "Ilania",
  "אילת": "Eilat",
  "אירוס": "Irus",
  "איתמר": "Itamar",
  "איתן": "Eitan",
  "אכסאל": "Iksal",
  "אל סייד": "AlSayid",
  "אל עזי": "Al Azi",
  "אל פורעה": "El For'eh",
  "אל רום": "El Rom",
  "אלומה": "Aluma",
  "אלומות": "Alumot",
  "אלון": "Alon",
  "אלון הגליל": "Alon HaGalil",
  "אלון מורה": "Elon Moreh",
  "אלון שבות": "Alon Shvut",
  "אלוני אבא": "Alonei Abba",
  "אלוני הבשן": "Alonei HaBashan",
  "אלונים": "Alonim",
  "אלי עד": "Eliad",
  "אליאב": "Eliav",
  "אליכין": "Elyachin",
  "אליפלט": "Elifelet",
  "אליקים": "Elyakim",
  "אלישיב": "Elyashiv",
  "אלישמע": "Elishema",
  "אלמגור": "Almagor",
  "אלמוג": "Almog",
  "אלעד": "Elad",
  "אלעזר": "Elazar",
  "אלפי מנשה": "Alfei Menashe",
  "אלקוש": "Alkosh",
  "אלקנה": "Elkana",
  "אמונים": "Emunim",
  "אמירים": "Amirim",
  "אמנון": "Amnon",
  "אמץ": "Amatz",
  "אניעם": "Aniam",
  "אעבלין": "Ibillin",
  "אעירה השחר": "Aira Shachar",
  "אפיק": "Afik",
  "אפיקים": "Afikim",
  "אפק": "Afek",
  "אפקה": "Afeka",
  "אפרת": "Efrat",
  "ארבל": "Arbel",
  "ארגמן": "Argaman",
  "ארז": "Erez",
  "אריאל": "Ariel",
  "ארסוף": "Arsuf",
  "אש קודש": "Esh Kodesh",
  "אשבול": "Eshbol",
  "אשבל": "Eshbal",
  "אשדוד - א,ב,ד,ה": "Ashdod - Alef, Bet, Dalet, Heh",
  "אשדוד - איזור תעשייה צפוני": "Ashdod - Northen Industrial Zone",
  "אשדוד - ג,ו,ז": "Ashdod - Gimmel, Vav, Zain",
  "אשדוד - ח,ט,י,יג,יד,טז": "Ashdod - Het, Tet, Yod, Yod Gimmel, Yod Dalet, Te*",
  "אשדות יעקב": "Ashdot Yaacov",
  "אשחר": "Eshchar",
  "אשכולות": "Eshkolot",
  "אשל הנשיא": "Eshel HaNassi",
  "אשלים": "Ashalim",
  "אשקלון - דרום": "Ashkelon - South",
  "אשקלון - צפון": "Ashkelon - North",
  "אשרת": "Oshrat",
  "אשתאול": "Eshtaol",
  "אשתמוע": "Eshtemoa",
  "אתר דודאים": "Duda'im Site",
  "אתר ההנצחה גולני": "Golani Memorial Site",
  "באקה אל גרבייה": "Bqa Al-Gharbiyye",
  "באר גנים": "Be'er Ganim",
  "באר טוביה": "Be'er Tuvia",
  "באר יעקב": "Be'er Yacov",
  "באר מילכה": "Be'er Milka",
  "באר שבע - דרום": "Beer Sheva - South",
  "באר שבע - מזרח": "Beer Sheva - East",
  "באר שבע - מערב": "Beer Sheva - West",
  "באר שבע - צפון": "Beer Sheva - North",
  "בארות יצחק": "Be'erot Itzhak",
  "בארותיים": "Be'erotaim",
  "בארי": "Be'eri",
  "בוסתן הגליל": "Bustan HaGalil",
  "בועיינה-נוג'ידאת": "Bu'eine Nujeidat",
  "בוקעתא": "Buq'ata",
  "בורגתה": "Burgata",
  "בחן": "Bahan",
  "בטחה": "Bitha",
  "ביצרון": "Bitzaron",
  "ביר אלמכסור": "Bir Al-Maksur",
  "ביר הדאג'": "Bir Hadaj",
  "ביריה": "Biriyeh",
  "בית אורן": "Beit Oren",
  "בית אל": "Beit El",
  "בית אלעזרי": "Beit Elazari",
  "בית אלפא וחפציבה": "Beit Alfa And Heftziba",
  "בית אריה": "Beit Arie",
  "בית ברל": "Beit Berl",
  "בית ג'אן": "Beit Jann",
  "בית גוברין": "Beit Guvrin",
  "בית גמליאל": "Beit Gamliel",
  "בית דגן": "Beit Dagan",
  "בית הברכה": "Beit HaBracha",
  "בית הגדי": "Beit HaGdi",
  "בית הלוי": "Beit HaLevi",
  "בית הלל": "Beit Hillel",
  "בית העלמין החדש נהריה": "Nahariya Cemetery",
  "בית העלמין החדש עכו": "Akko New Cemetery",
  "בית העמק": "Beit HaEmek",
  "בית הערבה": "Beit HaArava",
  "בית השיטה": "Beit HaShita",
  "בית זית": "Beit Zayit",
  "בית זרע": "Beit Zera",
  "בית חג\"י": "Beit Hagai",
  "בית חגלה": "Beit Hogla",
  "בית חורון": "Beit Horon",
  "בית חלקיה": "Beit Hilkia",
  "בית חנן": "Beit Hanan",
  "בית חרות": "Beit Herut",
  "בית חשמונאי": "Beit Hashmonai",
  "בית יהושע": "Beit Yehoshua",
  "בית יוסף": "Beit Yossef",
  "בית ינאי": "Beit Yannai",
  "בית יצחק - שער חפר": "Beit Yithak - Sha'ar Hefer",
  "בית ירח": "Beit Yerah",
  "בית יתיר": "Beit Yatir",
  "בית לחם הגלילית": "Bethlehem of Galilee",
  "בית מאיר": "Beit Meir",
  "בית נחמיה": "Beit Nechemia",
  "בית ניר": "Beit Nir",
  "בית נקופה": "Beit Nekofa",
  "בית סוהר צלמון": "Zalmon Prison",
  "בית סוהר קישון": "Kishon Prison",
  "בית ספר שדה מירון": "Sdeh Meron School",
  "בית עובד": "Beit Oved",
  "בית עוזיאל": "Beit Uziel",
  "בית עזרא": "Beit Ezra",
  "בית עלמין מורשה": "Morasha Cemetery",
  "בית עלמין תל רגב": "Tel Regev Cemetary",
  "בית עריף": "Beit Arif",
  "בית צבי": "Beit Zvi",
  "בית קמה": "Beit Kama",
  "בית קשת": "Beit Keshet",
  "בית רימון": "Beit Rimon",
  "בית שאן": "Beit She'an",
  "בית שמש": "Beit Shemesh",
  "בית שערים": "Beit Shea'rim",
  "בית שקמה": "Beit Shikma",
  "ביתן אהרן": "Bitan Aharon",
  "ביתר עילית": "Beitar Illit",
  "בלפוריה": "Balfuria",
  "בן זכאי": "Ben Zakai",
  "בן עמי": "Ben Ami",
  "בן שמן": "Ben Shemen",
  "בני אדם": "Beni Adam",
  "בני ברק": "Bnei Brak",
  "בני דקלים": "Bnei Dkalim",
  "בני דרום": "Bnei Darom",
  "בני דרור": "Bnei Dror",
  "בני יהודה וגבעת יואב": "Bnei Yehuda And Givat Yoav",
  "בני נצרים": "Bnei Netzarim",
  "בני עטרות": "Bnei Atarot",
  "בני ציון": "Bnei Zion",
  "בני ראם": "Bnei Re'em",
  "בניה": "Bnaya",
  "בסמת טבעון": "Basmat Tab'un",
  "בענה": "Bi'ina",
  "בצרה": "Batzra",
  "בצת": "Betzet",
  "בקוע": "Beko'a",
  "בקעות": "Beka'ot",
  "בר גיורא": "Bar Giora",
  "בר יוחאי": "Bar Yochai",
  "בר כוכבא": "Bar Kokhba",
  "ברוכין": "Brukhin",
  "ברור חיל": "Bror Hayil",
  "ברוש": "Brosh",
  "ברטעה": "Bart'a",
  "ברכיה": "Berekhya",
  "ברעם": "Baram",
  "ברקאי": "Barkai",
  "ברקן": "Barkan",
  "ברקת": "Bareket",
  "בת הדר": "Bat Hadar",
  "בת חן": "Bat Chen",
  "בת חפר": "Bat Hefer",
  "בת ים": "Bat-Yam",
  "בת עין": "Bat Ayin",
  "בתי מלון ים המלח": "Dead Sea Hotels",
  "בתרונות": "Bitronot",
  "ג'דידה מכר": "Jadeidi-Makr",
  "ג'וליס": "Julis",
  "ג'לג'וליה": "Jaljulia",
  "ג'ש - גוש חלב": "Jish (Gush Halav)",
  "ג'ת": "Jatt",
  "גאולי תימן": "Geulei Teiman",
  "גאולים": "Geulim",
  "גאליה": "Ge'alya",
  "גבולות": "Gvulot",
  "גבים, מכללת ספיר": "Gavim, Sapir College",
  "גבע בנימין": "Geva Binyamin",
  "גבע כרמל": "Geva Carmel",
  "גבעון החדשה": "Givon HaHadasha",
  "גבעות": "Gvaot",
  "גבעות בר": "Giv'ot Bar",
  "גבעות עדן": "Giv'ot Eden",
  "גבעת אבני": "Giv'at Avni",
  "גבעת אלה": "Givat Ela",
  "גבעת אסף": "Giv'at Asaf",
  "גבעת ברנר": "Givat Brenner",
  "גבעת הראל": "Givat Harel",
  "גבעת הרואה": "Givat Ha-Roe",
  "גבעת השלושה": "Givat HaShlosha",
  "גבעת וולפסון": "Givat Wolfson",
  "גבעת וושינגטון": "Givat Washington",
  "גבעת זאב": "Givat Ze'ev",
  "גבעת חיים איחוד": "Givat Haim (Ihud)",
  "גבעת חיים מאוחד": "Givat Haim (Meuhad)",
  "גבעת חן": "Givat Hen",
  "גבעת יערים": "Givat Yearim",
  "גבעת ישעיהו": "Givat Ishayahu",
  "גבעת עוז": "Givat Oz",
  "גבעת פורת יוסף": "Givat Porat Yosef",
  "גבעת שמואל": "Givat Shmuel",
  "גבעת שפירא": "Givat Shapira",
  "גבעתי": "Givati",
  "גבעתיים": "Givatayim",
  "גברעם": "Gvaram",
  "גבת": "Gvat",
  "גדות": "Gadot",
  "גדעונה": "Gidona",
  "גדרה": "Gdera",
  "גונן": "Gonen",
  "גופנה": "Gofna",
  "גורן": "Goren",
  "גורנות הגליל": "Gornot HaGalil",
  "גזית": "Gazit",
  "גזר": "Gezer",
  "גיאה": "Ge'a",
  "גיבתון": "Gibton",
  "גיזו": "Gizo",
  "גילת": "Gilat",
  "גינוסר": "Ginosar",
  "גינתון": "Ginaton",
  "גיתה": "Gita",
  "גיתית": "Gitit",
  "גלאון": "Galon",
  "גלגל": "Gilgal",
  "גמזו": "Gimzo",
  "גן הדרום": "Gan HaDarom",
  "גן השומרון": "Gan HaShomron",
  "גן חיים": "Gan Haim",
  "גן יאשיה": "Gan Yoshia",
  "גן יבנה": "Gan Yavne",
  "גן נר": "Gan Ner",
  "גן שורק": "Gan Sorek",
  "גן שלמה": "Gan Shlomo",
  "גן שמואל": "Gan Shmuel",
  "גנות": "Ganot",
  "גנות הדר": "Ginot Hadar",
  "גני הדר": "Ganei Hadar",
  "גני חוגה": "Ganey Hugga",
  "גני טל": "Ganei Tal",
  "גני יוחנן": "Ganei Yochanan",
  "גני עם": "Ganei Am",
  "גני תקווה": "Ganei Tikva",
  "גניגר": "Genigar",
  "געש": "Ga'ash",
  "געתון": "Ga'aton",
  "גפן": "Geffen",
  "גשור": "Gshur",
  "גשר": "Gesher",
  "גשר הזיו": "Gesher HaZiv",
  "גת": "Gat",
  "גת רימון": "Gat Rimon",
  "דבוריה": "Daburiyya",
  "דביר": "Dvir",
  "דברת": "Dovrat",
  "דגניה א": "Degania Alef",
  "דגניה ב": "Degania Bet",
  "דולב": "Dolev",
  "דורות": "Dorot",
  "דורות עילית": "Dorot Illit",
  "דחי": "Ed-Dahi",
  "דימונה": "Dimona",
  "דיר אל-אסד": "Deir Al-Asad",
  "דיר חנא": "Deir Hanna",
  "דישון": "Dishon",
  "דלית אל כרמל": "Daliyat Al-Karmel",
  "דלתון": "Dalton",
  "דמיידה": "Dmeide",
  "דפנה": "Dafna",
  "דקל": "Dekel",
  "האון": "Ha'On",
  "הבונים": "HaBonim",
  "הגבעה הצהובה": "The Yellow Hill",
  "הגושרים": "HaGoshrim",
  "הדר עם": "Hadar Am",
  "הוד השרון": "Hod HaSharon",
  "הודיה": "Hodaya",
  "הודיות": "Hodayot",
  "הושעיה": "Hoshaya",
  "הזורעים": "HaZor'im",
  "החווה של אורי כהן": "Uri Cohen's Farm",
  "החווה של זוהר": "Zohar's Farm",
  "החווה של יאיא": "Yaya's Farm",
  "החווה של מנחם": "Menachem's Farm",
  "החווה של עשהאל": "Asa'el's Farm",
  "החותרים": "HaHotrim",
  "היוגב": "HaYogev",
  "היישוב היהודי חברון": "Hevron Jewish Settlement",
  "הילה": "Hila",
  "המעפיל": "HaMa'apil",
  "המרכז האקדמי רופין": "Ruppin Academic Center",
  "הסוללים": "HaSollelim",
  "העוגן": "HaOgen",
  "הר אדר": "Har Adar",
  "הר ברכה": "Har Bracha",
  "הר גילה": "Har Gilo",
  "הר חלוץ": "Har Halutz",
  "הר עמשא": "Har Amsha",
  "הראל": "Harel",
  "הרדוף": "Harduf",
  "הרצליה - מערב": "Herzliya - West",
  "הרצליה - מרכז וגליל ים": "Herzeliya - Center And Glil Yam",
  "הררית יחד": "Hararit Yachad",
  "ואדי אל חמאם": "Wadi Hamam",
  "ואדי אל נעם דרום": "Wadi El Na'am South",
  "ורד יריחו": "Vered Yericho",
  "ורדון": "Vardon",
  "זבדיאל": "Zavdiel",
  "זוהר": "Zohar",
  "זיתן": "Zeitan",
  "זכריה": "Zekharia",
  "זמר": "Zemer",
  "זמרת, שובה": "Zimrat, Shuva",
  "זנוח": "Zanoah",
  "זרועה": "Zru'a",
  "זרזיר": "Zarzir",
  "זרחיה": "Zrahia",
  "זרעית": "Zarit",
  "חבצלת השרון וצוקי ים": "Havatzelet HaSharon And Tzukei Yam",
  "חג'אג'רה": "Hajajre",
  "חגור": "Hagor",
  "חגלה": "Hogla",
  "חד נס": "Had Ness",
  "חדיד": "Hadid",
  "חדרה - מזרח": "Hadera - East",
  "חדרה - מערב": "Hadera - West",
  "חדרה - מרכז": "Hadera - Center",
  "חדרה - נווה חיים": "Hadera - Neveh Haim",
  "חוות אביה": "Havat Avia",
  "חוות אביחי": "Havat Avihai",
  "חוות אל נווה": "Havat El Naveh",
  "חוות אלחי": "Havat Elchai",
  "חוות ארץ האיילים": "Havat Eretzh Ha'Ayalim",
  "חוות אשכולות": "Havat Eshkolot",
  "חוות בניהו": "Havat Bnayahu",
  "חוות גלעד": "Havat Gil'ad",
  "חוות גנות": "Havat Ganot",
  "חוות דרומא": "Havat Daroma",
  "חוות הרועה העברי": "Havat Haroe Haivri",
  "חוות הרשאש": "Rashash Farm",
  "חוות חנינא": "Havat Hanina",
  "חוות טואמין": "Havat Toamin",
  "חוות טליה": "Havat Taliya",
  "חוות יאיר": "Havat Yair",
  "חוות יד השומר": "Havat Yad HaShomer",
  "חוות יויו": "Havat Yoyo",
  "חוות ינון": "Havat Yenon",
  "חוות מגדלים": "Havat Megadlim",
  "חוות מגנזי": "Havat Maginzi",
  "חוות מדבר חבר": "Havat Midbar Haver",
  "חוות מור ואברהם": "Havat Mor Ve'Avraham",
  "חוות מלאכי אברהם": "Havat Malchei Avraham",
  "חוות מלכיאל": "Havat Malkiel",
  "חוות מנחם": "Havat Menachem",
  "חוות מעלה אהוביה": "Havat Ma'ale Ahuvia",
  "חוות מקנה יהודה": "Havat Mikne Yehuda",
  "חוות מרום שמואל": "Havat Marom Shmuel",
  "חוות נווה צוף": "Havat Neve Zuf",
  "חוות נוף אב\"י": "Havat Nof Avi",
  "חוות נחל שילה": "Havat Hanal Shilo",
  "חוות נחלת אבות": "Havat Nahlat Avot",
  "חוות נחלת צבי": "Havat Nahalat Tzvi",
  "חוות עדן": "Havat Eden",
  "חוות עולם חסד": "Havat Olam Hesed",
  "חוות עמיאל": "Havat Amiel",
  "חוות פריאל": "Havat Priel",
  "חוות צאן קדר": "Havat Tzon Kedar",
  "חוות צרידה": "Havat Zrida",
  "חוות קשואלה": "Havat Kashuala",
  "חוות ראש תאנה": "Havat Rosh Teena",
  "חוות שדה": "Havat Sade",
  "חוות שוביאל": "Havat Shuviel",
  "חוות שחרית": "Havat Shaharit",
  "חוות תלם צפון": "Havat Telem North",
  "חולדה": "Hulda",
  "חולון": "Holon",
  "חולית": "Holit",
  "חולתה": "Hulata",
  "חומש": "Homesh",
  "חוסן": "Hossen",
  "חוסנייה": "Hussniyya",
  "חוף אכזיב": "Hof Achziv",
  "חוף בצת": "Betzet Beach",
  "חוף קליה": "Kalia Beach",
  "חופית": "Hofit",
  "חוקוק": "Hukok",
  "חורה": "Hura",
  "חורפיש": "Hurfeish",
  "חורשים": "Horashim",
  "חזון": "Hazon",
  "חיבת ציון": "Hibat Zion",
  "חיפה - בת גלים ק.אליעזר": "Haifa - Bat Galim, Kiryat Eliezer",
  "חיפה - כרמל, הדר ועיר תחתית": "Haifa - Carmel, Hadar And Downtown Lower City",
  "חיפה - מערב": "Haifa - West",
  "חיפה - מפרץ": "Haifa - Bay",
  "חיפה - נווה שאנן ורמות כרמל": "Haifa - Ramot HaCarmel And Neveh Sha'anan",
  "חיפה - קריית חיים ושמואל": "Haifa - Kiryat Haim & Kiryat Shmuel",
  "חירן": "Hiran",
  "חלץ": "Heletz",
  "חמד": "Hemed",
  "חמדיה": "Hamadia",
  "חמדת": "Hemdat",
  "חמדת ימים": "Hemdat Yamim",
  "חמרה": "Hamra",
  "חמת גדר": "Hamat Gader",
  "חניאל": "Haniel",
  "חניון רעים אנדרטת הנובה": "Nova Festival Victims Memorial Reim Parking",
  "חניתה": "Hanita",
  "חנתון": "Hanaton",
  "חספין": "Haspin",
  "חפץ חיים": "Hafetz Haim",
  "חצב": "Hatzav",
  "חצור": "Hatzor",
  "חצור הגלילית": "Hatzor HaGlilit",
  "חצרים": "Hatzerim",
  "חרב לאת": "Herev Le'Et",
  "חרוצים": "Harutzim",
  "חרות": "Herut",
  "חריש": "Harish",
  "חרמש": "Hermesh",
  "חרמש דרום": "Hermesh South",
  "חרשה": "Horasha",
  "חרשים": "Harashim",
  "חשמונאים": "Hashmonaim",
  "טבריה": "Tiberias",
  "טובא זנגריה": "Tuba-Zangariyye",
  "טורעאן": "Turan",
  "טייבה": "Tayibe",
  "טייבה בגלבוע": "Taibe (Gilboa)",
  "טירה": "Tira",
  "טירת יהודה": "Tirat Yehuda",
  "טירת כרמל": "Tirat Carmel",
  "טירת צבי": "Tirat Zvi",
  "טל - אל": "Tal-El",
  "טל שחר": "Tal Shachar",
  "טללים": "Tlalim",
  "טלמון": "Talmon",
  "טמרה": "Tamra",
  "טמרה בגלבוע": "Tamra (Gilboa)",
  "טנא עומרים": "Teneh Omarim",
  "טפחות": "Tefahot",
  "יבוא דודי": "Yevo Dodi",
  "יבנאל": "Yavne'el",
  "יבנה": "Yavne",
  "יגור": "Yagur",
  "יגל": "Yagel",
  "יד בנימין": "Yad Binyamin",
  "יד השמונה": "Yad HaShmona",
  "יד חנה": "Yad Hana",
  "יד מרדכי": "Yad Mordechai",
  "יד נתן": "Yad Natan",
  "יהוד מונוסון": "Yehud - Monoson",
  "יובלים": "Yuvalim",
  "יודפת": "Yodfat",
  "יונתן": "Yonatan",
  "יושיביה": "Yoshivia",
  "יזרעאל": "Yizre'el",
  "יחיעם": "Yechiam",
  "יכיני": "Yakhini",
  "ינוב": "Yanuv",
  "ינוח ג'ת": "Yanuh-Jat",
  "ינון": "Yinon",
  "יסוד המעלה": "Yesud Hama'ala",
  "יסודות": "Yesodot",
  "יסעור": "Yasur",
  "יעבץ, יעף": "Yavetz, Ye'af",
  "יעד": "Ya'ad",
  "יערה": "Ya'ara",
  "יפיע": "Yafia",
  "יפית": "Yafit",
  "יפעת": "Ifat",
  "יפתח": "Iftach",
  "יצהר": "Itzhar",
  "יציץ": "Yatzitz",
  "יקום": "Yakum",
  "יקיר": "Yakir",
  "יקנעם המושבה והזורע": "Yokneam Moshava And HaZoreah",
  "יקנעם עילית": "Yokneam Illit",
  "יראון": "Yir'on",
  "ירדנה": "Yardena",
  "ירוחם": "Yeruham",
  "ירושלים - אזור תעשייה עטרות": "Jerusalem - Atarot Industrial Zone",
  "ירושלים - דרום": "Jerusalem - South",
  "ירושלים - כפר עקב": "Jerusalem - Qafr 'Aqab",
  "ירושלים - מזרח": "Jerusalem - East",
  "ירושלים - מערב": "Jerusalem - West",
  "ירושלים - מרכז": "Jerusalem - Center",
  "ירושלים - צפון": "Jerusalem - North",
  "ירחיב": "Yafhiv",
  "ירכא": "Yarka",
  "ירקונה": "Yarkona",
  "ישובי אומן": "Omen Settlements",
  "ישובי יעל": "Yael Settlements",
  "ישעי": "Yish'i",
  "ישרש": "Yashresh",
  "יתד": "Yated",
  "כאבול": "Kabul",
  "כאוכב אבו אלהיג'א": "Kaukab Abu Al-Hija",
  "כברי": "Cabri",
  "כדורי": "Kadoorie",
  "כוכב השחר": "Kokhav HaShahar",
  "כוכב יאיר - צור יגאל": "Kokhav Ya'ir - Tzur Yigal",
  "כוכב יעקב": "Kokhav Ya'akov",
  "כוכב מיכאל": "Kokhav Michael",
  "כורזים ורד הגליל": "Korazim Vered HaGalil",
  "כחל": "Kahal",
  "כינרת מושבה": "Moshavat Kinneret",
  "כינרת קבוצה": "Kvutzat Kinneret",
  "כיסופים": "Kissufim",
  "כישור": "Kishor",
  "כליל": "Klil",
  "כלנית": "Kalanit",
  "כמון - כמאנה מזרחית": "Kamon - Kamane East",
  "כנות": "Kannot",
  "כנף": "Kanaf",
  "כסייפה": "Kuseife",
  "כסלון": "Ksalon",
  "כסרא סמיע": "Kisra-Sumei",
  "כעביה טבאש": "Ka'abiyye Tabbash",
  "כפר אביב": "Kfar Aviv",
  "כפר אדומים": "Kfar Edomim",
  "כפר אוריה": "Kfar Uriah",
  "כפר אחים": "Kfar Achim",
  "כפר אלדד": "Kfar Eldad",
  "כפר ביאליק": "Kfar Biyalik",
  "כפר בלום": "Kfar Blum",
  "כפר בן נון": "Kfar Bin Nun",
  "כפר ברא": "Kafr Bara",
  "כפר ברוך": "Kfar Baruch",
  "כפר גדעון": "Kfar Gidon",
  "כפר גלים": "Kfar Galim",
  "כפר גלעדי": "Kfar Giladi",
  "כפר דניאל": "Kfar Daniel",
  "כפר האורנים": "Kfar HaOranim",
  "כפר החורש": "Kfar HaHoresh",
  "כפר המכבי": "Kfar HaMaccabi",
  "כפר הנגיד": "Kfar HaNagid",
  "כפר הנוער קריית יערים": "Kiryat Ye'arim Youth Village",
  "כפר הנוקדים": "Kfar HaNokdim",
  "כפר הנשיא": "Kfar HaNassi",
  "כפר הס": "Kfar Hess",
  "כפר ויתקין": "Kfar Vitkin",
  "כפר ורבורג": "Kfar Warburg",
  "כפר ורדים": "Kfar Vradim",
  "כפר זוהרים": "Kfar Zoharim",
  "כפר זיתים": "Kfar Zeitim",
  "כפר ח'וואלד": "Khawaled Village",
  "כפר חיטים": "Kfar Hittim",
  "כפר חיים": "Kfar Haim",
  "כפר חנניה": "Kfar Hanania",
  "כפר חסידים": "Kfar Hassidim",
  "כפר חרוב": "Kfar Haruv",
  "כפר טרומן": "Kfar Truman",
  "כפר יאסיף": "Kfar Yassif",
  "כפר ידידיה": "Kfar Yedidia",
  "כפר יהושע": "Kfar Yehoshua",
  "כפר יובל": "Kfar Yuval",
  "כפר יונה": "Kfar Yona",
  "כפר יחזקאל": "Kfar Yechezkel",
  "כפר כמא": "Kfar Kama",
  "כפר כנא": "Kfar Kana",
  "כפר מונש": "Kfar Monash",
  "כפר מימון ותושיה": "Kfar Maimon And Tushia",
  "כפר מנדא": "Kfar Manda",
  "כפר מנחם": "Kfar Menachem",
  "כפר מסריק": "Kfar Masaryk",
  "כפר מצר": "Kafr Misr",
  "כפר מרדכי": "Kfar Mordechai",
  "כפר נהר הירדן": "Kfar Nehar HaYarden",
  "כפר נוער בן שמן": "Ben Shemen Youth Village",
  "כפר נטר": "Kfar Netter",
  "כפר סאלד": "Kfar Szold",
  "כפר סבא": "Kfar Saba",
  "כפר סילבר": "Kfar Silver",
  "כפר סירקין": "Kfar Sirkin",
  "כפר עבודה": "Kfar Avoda",
  "כפר עזה": "Kfar Azza",
  "כפר עציון": "Kfar Etzion",
  "כפר פינס": "Kfar Pinnes",
  "כפר קאסם": "Kfar Kassem",
  "כפר קיש": "Kfar Kish",
  "כפר רופין": "Kfar Ruppin",
  "כפר רות": "Kfar Rut",
  "כפר שמאי": "Kfar Shamai",
  "כפר שמואל": "Kfar Shmuel",
  "כפר שמריהו": "Kfar Shmaryahu",
  "כפר תבור": "Kfar Tavor",
  "כפר תפוח": "Kfar Tapuach",
  "כפר תקווה": "Kfar Tikva",
  "כרכום": "Karkom",
  "כרם ביבנה": "Kerem BeYavne",
  "כרם בן זמרה": "Kerem Ben Zimra",
  "כרם רעים": "Kerem Reim",
  "כרם שלום": "Kerem Shalom",
  "כרמי יוסף": "Karmei Yossef",
  "כרמי צור": "Karmei Tzur",
  "כרמי קטיף ואמציה": "Karmei Katif And Amatzia",
  "כרמיאל": "Karmiel",
  "כרמיה": "Karmia",
  "כרמים": "Kramim",
  "כרמית": "Carmit",
  "כרמל": "Carmel",
  "לב החולה": "Lev Ha-Hula",
  "לבון": "Lavon",
  "לביא": "Lavi",
  "לבנים": "Livnim",
  "להב": "Lahav",
  "להבות הבשן": "Lehavot HaBashan",
  "להבות חביבה": "Lehavot Haviva",
  "להבים": "Lehavim",
  "לוד": "Lod",
  "לוזית": "Luzit",
  "לוחמי הגטאות": "Lochamei HaGetaot",
  "לוטם וחמדון": "Lotem And Hamdon",
  "לטרון": "Latrun",
  "לימן": "Lehman",
  "לכיש": "Lakhish",
  "לפיד": "Lapid",
  "לפידות": "Lapidot",
  "לקיה": "Laqiya",
  "מאור": "Maor",
  "מבוא ביתר": "Mevo Beitar",
  "מבוא דותן": "Mevo Dotan",
  "מבוא חורון": "Mevo Horon",
  "מבוא חמה": "Mevo Hama",
  "מבוא מודיעים": "Mevo Modi'im",
  "מבואות יריחו": "Mevuot Yericho",
  "מבועים": "Mabu'im",
  "מבטחים, עמיעוז, ישע": "Mivtahim, Ami'oz, Yesha",
  "מבקיעים": "Mavki'im",
  "מבשרת ציון": "Mevasseret Zion",
  "מג'דל כרום": "Majd Al-Krum",
  "מג'דל שמס": "Majdal Shams",
  "מגדים": "Megadim",
  "מגדל": "Migdal",
  "מגדל העמק": "Migdal HaEmek",
  "מגדל עוז": "Migdal Oz",
  "מגדל תפן": "Migdal Tefen",
  "מגדלים": "Megadlim",
  "מגל": "Magal",
  "מגן": "Magen",
  "מגן שאול": "Magen Shaul",
  "מגרון": "Migron",
  "מגשימים": "Magshimim",
  "מדרך עוז": "Midrach Oz",
  "מודיעין - ישפרו סנטר": "Modi'in - Ishpro Center",
  "מודיעין - ליגד סנטר": "Modi'in - Ligad Center",
  "מודיעין מכבים רעות": "Modi'in Maccabim Re'ut",
  "מודיעין עילית": "Modi'in Illit",
  "מולדת": "Moledet",
  "מוצא עילית": "Motza Illit",
  "מורן": "Moran",
  "מורשת": "Moreshet",
  "מזור": "Mazor",
  "מזכרת בתיה": "Mazkeret Batya",
  "מזרע": "Mizra",
  "מזרעה": "Mazra'a",
  "מחולה": "Mehola",
  "מחניים": "Machanaim",
  "מחסיה": "Mahsiya",
  "מטווח ניר עם": "Nir Am Shooting Range",
  "מטולה": "Metulla",
  "מטע": "Mata",
  "מייסר": "Meiser",
  "מיני ישראל - נחשון": "Mini Israel - Nachshon",
  "מיצד": "Metzad",
  "מיצר": "Metzar",
  "מירון": "Meron",
  "מישר": "Meishar",
  "מיתר": "Meitar",
  "מכון וינגייט": "Wingate Institute",
  "מכורה": "Mekhora",
  "מכינת אלישע": "Elisha Preparatory",
  "מכמורת": "Mikhmoret",
  "מכמנים - כמאנה מערבית": "Mikhmanim - Kamane West",
  "מלאכי השלום": "Malachei HaShalom",
  "מלונות ים המלח מרכז": "Dead Sea Hotels - Center",
  "מלכיה": "Malkia",
  "מנוחה": "Menucha",
  "מנוף": "Manof",
  "מנות": "Manot",
  "מנחמיה": "Menahemia",
  "מנחת מחניים": "Machanaim Landing Pad",
  "מנרה": "Manara",
  "מנשית זבדה": "Manshiya Zabda",
  "מסד": "Massad",
  "מסדה": "Masada",
  "מסוף אורנית": "Oranit Terminal",
  "מסילות": "Messilot",
  "מסילת ציון": "Mesillat Zion",
  "מסלול": "Maslul",
  "מסעדה": "Mas'ade",
  "מע'אר": "Maghar",
  "מעברות": "Ma'abarot",
  "מעגלים, גבעולים, מלילות": "Ma'galim, Giv'olim, M'lilot",
  "מעגן": "Ma'agan",
  "מעוז חיים": "Maoz Haim",
  "מעון": "Ma'on",
  "מעון צופיה": "Maon Tzofia",
  "מעונה": "Maona",
  "מעיין ברוך": "Ma'ayan Baruch",
  "מעיליא": "Mi'ilya",
  "מעלה אדומים": "Ma'aleh Edomim",
  "מעלה אפרים": "Ma'aleh Ephraim",
  "מעלה גמלא": "Ma'aleh Gamla",
  "מעלה החמישה": "Ma'aleh HaHamisha",
  "מעלה חבר": "Ma'ale Hever",
  "מעלה לבונה": "Ma'aleh Levona",
  "מעלה מכמש": "Ma'aleh Michmash",
  "מעלה עמוס": "Ma'aleh Amos",
  "מעלה צביה": "Ma'aleh Zvia",
  "מעלה רחבעם": "Ma'ale Rekhav'am",
  "מעלות תרשיחא": "Ma'a Lot Tarshicha",
  "מענית, גבעת חביבה": "Maanit, Givat Haviva",
  "מעש": "Maas",
  "מפלסים": "Mefalsim",
  "מצדה": "Massada",
  "מצובה": "Metzuba",
  "מצוקי דרגות": "Metzokei Dragot",
  "מצליח": "Matzliach",
  "מצפה": "Mitzpeh",
  "מצפה אילן": "Mitzpeh Ilan",
  "מצפה דני": "Mitzpe Danny",
  "מצפה זי\"ו": "Mitzpe ZIV",
  "מצפה חגית": "Mitzpe Hagit",
  "מצפה יאיר": "Mitzpe Yair",
  "מצפה יריחו": "Mitzpeh Yericho",
  "מצפה מדרג": "Mitzpe Midrag",
  "מצפה נטופה": "Mitzpeh Netofa",
  "מצפה שלם": "Mitzpeh Shalem",
  "מצפור פצאל": "Mitzpor Fatsa'el",
  "מצר": "Metzer",
  "מקווה ישראל": "Mikveh Israel",
  "מרגליות": "Margaliot",
  "מרחביה מושב": "Merhavia Moshav",
  "מרחביה קיבוץ": "Merhavia Kibbutz",
  "מרחצאות עין גדי": "Ein Gedi Baths",
  "מרכז אזורי דרום השרון": "Southern Sharon Regional Center",
  "מרכז אזורי מבואות חרמון": "Mevuot Hermon Regional Council",
  "מרכז אזורי מגילות": "Megilot Regional Center",
  "מרכז אזורי מרום גליל": "Marom HaGalil Regional Center",
  "מרכז אזורי משגב": "Misgav Regional Center",
  "מרכז אזורי רמת כורזים": "Ramat Korazim Regional Center",
  "מרכז חבר": "Merkaz Hever",
  "מרכז שפירא": "Merkaz Shapira",
  "מרעית": "Mar'it",
  "משאבי שדה": "Mashabei Sadeh",
  "משגב דב": "Misgav Dov",
  "משגב עם": "Misgav Am",
  "משהד": "Mashhad",
  "משואה": "Masua",
  "משואות יצחק": "Masuot Itzhak",
  "משכיות": "Maskiot",
  "משמר איילון": "Mishmar Ayalon",
  "משמר דוד": "Mishmar David",
  "משמר הירדן": "Mishmar HaYarden",
  "משמר הנגב": "Mishmar HaNegev",
  "משמר העמק": "Mishmar HaEmek",
  "משמר השבעה": "Mishmar HaShiva",
  "משמר השרון": "Mishmar HaSharon",
  "משמרת": "Mishmeret",
  "משען": "Mishan",
  "מתחם בני דרום": "Bnei Darom Compound",
  "מתחם גלילות": "Glilot Complex",
  "מתחם סקי גלבוע": "Gilboa Ski Resort",
  "מתחם פי גלילות": "Gelilot - Pi Compound",
  "מתחם שביל התפוזים": "Shvil HaTapuzim Compound",
  "מתן": "Matan",
  "מתת": "Matat",
  "מתתיהו": "Matityahu",
  "נאות גולן": "Neot Golan",
  "נאות מרדכי": "Neot Mordechai",
  "נאות קדומים": "Neot Kedumim",
  "נאעורה": "Na'ura",
  "נבטים": "Nevatim",
  "נבי שועייב": "Nabi Shu'ayb",
  "נגבה": "Negba",
  "נגוהות": "Negohot",
  "נהורה": "Nehora",
  "נהלל": "Nahalal",
  "נהריה": "Nahariya",
  "נוב": "Nov",
  "נוגה": "Noga",
  "נוה איתן": "Neve Eitan",
  "נווה": "Naveh",
  "נווה אור": "Neveh Or",
  "נווה אילן": "Neveh Ilan",
  "נווה ארז": "Neveh Erez",
  "נווה דניאל": "Neveh Daniel",
  "נווה זוהר": "Neveh Zohar",
  "נווה זיו": "Neveh Ziv",
  "נווה ים": "Neveh Yam",
  "נווה ימין": "Neveh Yamin",
  "נווה ירק": "Neveh Yarak",
  "נווה מבטח": "Neveh Mivtach",
  "נווה מיכאל - רוגלית": "Neveh Michael (Rogalit)",
  "נווה צוף": "Neveh Tzuf",
  "נווה שלום": "Neveh Shalom",
  "נועם": "Noam",
  "נוף איילון, שעלבים": "Nof Ayalon, Sha'alvim",
  "נוף הגליל": "Nof HaGalil",
  "נופי נחמיה": "Nofei Nehemiah",
  "נופי פרת": "Nofei Prat",
  "נופים": "Nofim",
  "נופית": "Nofit",
  "נופך": "Nofech",
  "נוקדים": "Nokdim",
  "נורדיה": "Nordia",
  "נורית": "Nurit",
  "נחושה": "Nehusha",
  "נחל עוז": "Nachal Oz",
  "נחלה": "Nachla",
  "נחליאל": "Nachliel",
  "נחלים": "Nechalim",
  "נחם": "Naham",
  "נחף": "Nachaf",
  "נחשון": "Nachshon",
  "נחשונים": "Nachshonim",
  "נטועה": "Netua",
  "נטור": "Natur",
  "נטע": "Neta",
  "נטעים": "Neta'im",
  "נטף": "Nataf",
  "נילי": "Nili",
  "נין": "Nin",
  "ניצן": "Nitzan",
  "ניצני עוז": "Nitzanei Oz",
  "ניצנים": "Nitzanim",
  "ניר אליהו": "Nir Eliyahu",
  "ניר בנים": "Nir Banim",
  "ניר גלים": "Nir Galim",
  "ניר דוד": "Nir David",
  "ניר יצחק": "Nir Itzhak",
  "ניר ישראל": "Nir Israel",
  "ניר משה": "Nir Moshe",
  "ניר עוז": "Nir Oz",
  "ניר עם": "Nir Am",
  "ניר עציון, ימין אורד": "Nir Etsion, Yamin Orde",
  "ניר עקיבא": "Nir Akiva",
  "ניר צבי": "Nir Zvi",
  "נירים": "Nirim",
  "נירית": "Nirit",
  "נס הרים": "Ness Harim",
  "נס עמים": "Ness Amim",
  "נס ציונה": "Ness Ziona",
  "נעורים": "Neurim",
  "נעלה": "Na'aleh",
  "נעמה": "Na'ama",
  "נען": "Na'an",
  "נערן": "Niran",
  "נצר חזני": "Netzer Hazani",
  "נצר סרני": "Netzer Sireni",
  "נצרת": "Nazareth",
  "נריה": "Neria",
  "נשר": "Nesher",
  "נתיב הגדוד": "Netiv HaGdud",
  "נתיב העשרה": "Netiv HaAssara",
  "נתיב השיירה": "Netiv HaShayara",
  "נתיבות": "Netivot",
  "נתניה - מזרח": "Netanya - East",
  "נתניה - מערב": "Netanya - West",
  "סאג'ור": "Sajur",
  "סאסא": "Sassa",
  "סביון": "Savyon",
  "סגולה": "Sgula",
  "סואעד חמירה": "Sawad Humeria",
  "סולם": "Sulam",
  "סוסיא": "Susya",
  "סוסיא הקדומה": "Ancient Susya",
  "סופה": "Sufa",
  "סכנין": "Sakhnin",
  "סלמה": "Salama",
  "סלעית": "Salit",
  "סנדלה": "Sandala",
  "סנסנה": "Sansana",
  "סעד": "Sa'ad",
  "סעווה": "Sa'wa",
  "סער": "Sa'ar",
  "ספסופה - כפר חושן": "Safsufa (Kfar Hoshen)",
  "סתריה": "Sitria",
  "ע'ג'ר": "Ghajar",
  "עבדון": "Avdon",
  "עברון": "Evron",
  "עגור": "Agur",
  "עדי": "Adi",
  "עדי עד": "Adei Ad",
  "עדנים": "Adanim",
  "עוז וגאון": "Oz Ve'Gaon",
  "עוזה": "Uzza",
  "עוזייר, רומאנה": "Uzeir, Romana",
  "עולש": "Olesh",
  "עומר": "Omer",
  "עופרים": "Ofarim",
  "עוצם": "Otzem",
  "עזר": "Ezer",
  "עזריאל": "Azriel",
  "עזריה": "Azaria",
  "עזריקם": "Azrikam",
  "עטרת": "Atteret",
  "עיינות": "Ayanot",
  "עילבון": "Eilabun",
  "עילוט": "Ilut",
  "עין איילה": "Ein Ayala",
  "עין אל אסד": "Ein Al-Asad",
  "עין אל סהלה": "Ayn Al-Sahla",
  "עין בוקק": "Ein Bokek",
  "עין גב": "Ein Gev",
  "עין גדי": "Ein Gedi",
  "עין דור": "Ein Dor",
  "עין הבשור": "Ein HaBsor",
  "עין הוד": "Ein Hod",
  "עין החורש": "Ein HaHoresh",
  "עין המפרץ": "Ein HaMifratz",
  "עין העמק": "Ein HaEmek",
  "עין השופט": "Ein HaShofet",
  "עין השלושה": "Ein HaShlosha",
  "עין ורד": "Ein Vered",
  "עין חוד": "Ein Chod",
  "עין חרוד, תל יוסף": "Ein Harod, Tel Yosef",
  "עין יעקב": "Ein Yacov",
  "עין כרמל": "Ein Carmel",
  "עין מאהל": "Ein Mahil",
  "עין נקובא": "Ein Naqquba",
  "עין עירון": "Ein Iron",
  "עין צורים": "Ein Tzurim",
  "עין ראפה": "Ein Rafa",
  "עין שמר": "Ein Shemer",
  "עין שריד": "Ein Sarid",
  "עינות קדם": "Einot Kedem",
  "עינת": "Einat",
  "עכו": "Acre",
  "עכו - אזור תעשייה": "Acco - Industrial Zone",
  "עכו - רמות ים": "Acre - Ramot Yam",
  "עלומים": "Alumim",
  "עלי": "Eli",
  "עלי זהב - לשם": "Alei Zahav - Leshem",
  "עלמה": "Alma",
  "עלמון": "Almon",
  "עמוקה": "Amuka",
  "עמיחי": "Amichai",
  "עמינדב": "Aminadav",
  "עמיעד": "Amiad",
  "עמיר": "Amir",
  "עמנואל": "Immanuel",
  "עמקה": "Amka",
  "ענב": "Einav",
  "עספיא": "Isfiya",
  "עפולה": "Afula",
  "עפרה": "Ofra",
  "עץ אפרים": "Etz Ephraim",
  "עצמון - שגב": "Atzmon (Segev)",
  "עראבה": "Arraba",
  "ערב אל נעים": "Arab Al Naim",
  "ערב אל עראמשה": "Arab Al-Aramshe",
  "ערד": "Arad",
  "ערוגות": "Arugot",
  "ערערה בנגב": "Ar'ara BaNegev",
  "עשהאל": "Asa'el",
  "עשרת": "Asseret",
  "עתלית": "Atlit",
  "עתניאל": "Otniel",
  "פארק אריאל שרון": "Ariel Sharon Park",
  "פארק תעשיות מגדל עוז": "Industrial Park Migdal Oz",
  "פארק תעשיות פלמחים": "Palmachin Industrial Park",
  "פארק תעשייה ראם": "Re'em Industrial Park",
  "פדואל": "Paduel",
  "פדויים": "Pduim",
  "פדיה": "Pdaya",
  "פוריה כפר עבודה": "Poria - Kfar Avoda",
  "פוריה נווה עובד": "Poria - Neve Oved",
  "פוריה עילית": "Poria Illit",
  "פורת": "Porat",
  "פטיש": "Patish",
  "פלך": "Pelekh",
  "פלמחים": "Palmachim",
  "פני קדם": "Pnei Kedem",
  "פנימיית עין כרם": "Ein Kerem Boarding School",
  "פסגות": "Psagot",
  "פסוטה": "Fassuta",
  "פצאל": "Petza'el",
  "פקיעין": "Peki'in",
  "פקיעין החדשה": "Peki'in HaHadasha",
  "פרדס חנה כרכור": "Pardes Hanna - Kakur",
  "פרדסיה": "Pardessiya",
  "פרוד": "Farod",
  "פרי גן": "Pri Gan",
  "פתח תקווה": "Petach Tikva",
  "פתחיה": "Ptachia",
  "צאלים": "Ze'elim",
  "צבעון": "Zivon",
  "צובה": "Tzuba",
  "צוחר, אוהד": "Zohar, Ohad",
  "צומת אלמוג": "Almog Junction",
  "צומת הגוש": "Gush Etzion Junction",
  "צופים": "Zufim",
  "צופית": "Tzofit",
  "צור הדסה": "Tzur Hadassa",
  "צור יצחק": "Tzur Itzhak",
  "צור משה": "Tzur Moshe",
  "צור נתן": "Tzur Natan",
  "צוריאל": "Tzuriel",
  "צורית גילון": "Tzurit Gilon",
  "ציפורי": "Tzippori",
  "צלפון": "Tzalfon",
  "צמח": "Tsemach",
  "צפריה": "Tzafria",
  "צפרירים": "Tzafririm",
  "צפת - נוף כנרת": "Safed - Nof Ha-Kinneret",
  "צפת - עיר": "Safed - City",
  "צפת - עכברה": "Safed - 'Akbara",
  "צרופה": "Tzrufa",
  "צרעה": "Tzora",
  "קבוצת גבע": "Kvutzat Geva",
  "קבוצת יבנה": "Kvutzat Yavne",
  "קדומים": "Kdumim",
  "קדימה צורן": "Qadima - Zoran",
  "קדיתא": "Kadita",
  "קדם ערבה": "Kedem Arava",
  "קדמה": "Kedma",
  "קדמת צבי": "Kidmat Zvi",
  "קדר": "Kedar",
  "קדר דרום": "Kedar South",
  "קדרון": "Kidron",
  "קדרים": "Kadarim",
  "קוממיות": "Kommemiut",
  "קורנית": "Koranit",
  "קיבוץ דן": "Kibutz Dan",
  "קיבוץ מגידו": "Kibutz Megiddo",
  "קידה": "Kida",
  "קלחים": "Klachim",
  "קליה": "Kalia",
  "קלנסווה": "Qalansawe",
  "קלע אלון": "Kela Alon",
  "קסר א-סר": "Qasr Al-Sir",
  "קציר": "Katzir",
  "קצרין": "Katzrin",
  "קצרין - אזור תעשייה": "Katzrin - Industrial Area",
  "קריית אונו": "Kiryat Ono",
  "קריית אתא": "Kiryat Atta",
  "קריית ביאליק": "Kiryat Biyalik",
  "קריית גת, כרמי גת": "Kiryat Gat , Karmei Gat",
  "קריית חינוך מרחבים": "Merhavim Educational Campus",
  "קריית טבעון - בית זייד": "Kiryat Tivon - Beit Zaid",
  "קריית ים": "Kiryat Yam",
  "קריית יערים": "Kiryat Yearim",
  "קריית מוצקין": "Kiryat Motzkin",
  "קריית מלאכי": "Kiryat Malachi",
  "קריית נטפים": "Kiryat Netafim",
  "קריית ענבים": "Kiryat Anavim",
  "קריית עקרון": "Kiryat Ekron",
  "קריית שמונה": "Kiryat Shmona",
  "קרית ארבע": "Kiryat Arba",
  "קרני שומרון": "Karnei Shomron",
  "קשת": "Keshet",
  "ראמה": "Rama",
  "ראס אל-עין": "Ras Al-ein",
  "ראס עלי": "Ras Ali",
  "ראש הנקרה": "Rosh HaNikra",
  "ראש העין": "Rosh HaAyin",
  "ראש פינה": "Rosh Pinna",
  "ראש צורים": "Rosh Tzurim",
  "ראשון לציון - מזרח": "Rishon LeZion - East",
  "ראשון לציון - מערב": "Rishon LeZion - West",
  "רבבה": "Revava",
  "רבדים": "Revadim",
  "רביבים": "Revivim",
  "רביד": "Ravid",
  "רגבה": "Regba",
  "רהט": "Rahat",
  "רווחה": "Revacha",
  "רוחמה": "Rochama",
  "רומת אל הייב": "Rumat Al-Heib",
  "רועי": "Roee",
  "רותם": "Rotem",
  "רחובות": "Rehovot",
  "רחלים": "Rechelim",
  "רטורנו - גבעת שמש": "Retorno - Givat Shesh",
  "ריחאנייה": "Rehaniya",
  "ריחן": "Reihan",
  "ריינה": "Reineh",
  "רימונים": "Rimonim",
  "רינתיה": "Rinatya",
  "רכסים": "Rechasim",
  "רם און": "Ram On",
  "רמות": "Ramot",
  "רמות השבים": "Ramot HaShavim",
  "רמות מאיר": "Ramot Meir",
  "רמות נפתלי": "Ramot Naftali",
  "רמלה": "Ramla",
  "רמת גן - מזרח": "Ramat Gan - East",
  "רמת גן - מערב": "Ramat Gan - West",
  "רמת דוד": "Ramat David",
  "רמת הכובש": "Ramat HaKovesh",
  "רמת השופט": "Ramat HaShofet",
  "רמת השרון": "Ramat HaSharon",
  "רמת טראמפ": "Ramat Trump",
  "רמת יוחנן": "Ramat Yochana",
  "רמת ישי": "Ramat Ishai",
  "רמת מגרון": "Ramat Migron",
  "רמת מגשימים": "Ramat Magshimim",
  "רמת צבי": "Ramat Zvi",
  "רמת רזיאל": "Ramat Raziel",
  "רנן": "Renan",
  "רעים": "Reim",
  "רעננה": "Ra'anana",
  "רקפת": "Rakefet",
  "רשפון": "Rishpon",
  "רשפים, שלוחות, שלפים": "Reshafim, Shluchot, Shlafim",
  "רתמים": "Retamim",
  "שאר ישוב": "Shear Yeshuv",
  "שבות רחל": "Shvut Rachel",
  "שבי דרום": "Shavei Darom",
  "שבי ציון": "Shavei Zion",
  "שבי שומרון": "Shavei Shomron",
  "שגב שלום": "Segev Shalom",
  "שדה אילן": "Sdeh Ilan",
  "שדה אליהו": "Sdeh Eliyahu",
  "שדה אליעזר": "Sdeh Eliezer",
  "שדה אפרים": "Sde Efrayim",
  "שדה בועז": "Sde Boaz",
  "שדה בר": "Sdeh Bar",
  "שדה דוד": "Sdeh David",
  "שדה ורבורג": "Sdeh Warburg",
  "שדה יואב": "Sdeh Yoav",
  "שדה יעקב": "Sdeh Yacov",
  "שדה יצחק": "Sdeh Itzhak",
  "שדה משה": "Sdeh Moshe",
  "שדה נחום": "Sdeh Nachum",
  "שדה נחמיה": "Sdeh Nechemia",
  "שדה ניצן": "Sdeh Nitzan",
  "שדה עוזיהו": "Sdeh Uziahu",
  "שדה צבי": "Sdeh Zvi",
  "שדות מיכה": "Sdot Micha",
  "שדי אברהם": "Sdeh Avraham",
  "שדי חמד": "Sdei Hemed",
  "שדי תרומות": "Sdei Trumot",
  "שדמה": "Shdema",
  "שדמות דבורה": "Shadmot Dvora",
  "שדמות מחולה": "Shadmot Mechola",
  "שדרות, איבים": "Sderot, Ibim",
  "שואבה": "Shoeva",
  "שובל": "Shoval",
  "שוהם": "Shoham",
  "שומרה": "Shomera",
  "שומריה": "Shomria",
  "שוקדה": "Shokeda",
  "שורש": "Shoresh",
  "שורשים": "Shorashim",
  "שושנת העמקים": "Shoshanat Ha'Amakim",
  "שזור": "Shezor",
  "שחר": "Shachar",
  "שיבולים": "Shibolim",
  "שיבלי אום אלג'נם": "Shibli-Umm Al-Ghanam",
  "שייח' דנון": "Sheikh Danun",
  "שילה": "Shilo",
  "שילת": "Shilat",
  "שכניה": "Shekhanya",
  "שלווה": "Shalva",
  "שלומי": "Shlomi",
  "שלומית": "Shlomit",
  "שלומציון": "Shlomtsiyon",
  "שמיר": "Shamir",
  "שמעה": "Shim'a",
  "שמרת": "Shomrat",
  "שמשית": "Shimshit",
  "שני ליבנה": "Sheni LeYavne",
  "שניר": "Snir",
  "שעב": "Sha'ab",
  "שעל": "Sha'al",
  "שער אפרים": "Sha'ar Efraim",
  "שער הגולן": "Sha'ar HaGolan",
  "שער העמקים": "Sha'ar HaAmakim",
  "שער מנשה": "Sha'ar Menashe",
  "שערי תקווה": "Sha'arei Tikva",
  "שפיים": "Shefayim",
  "שפיר": "Shafir",
  "שפר": "Shefer",
  "שפרעם": "Shfaram",
  "שקד": "Shaked",
  "שקף": "Shekef",
  "שרונה": "Sharona",
  "שריגים - לי-און": "Srigim-Li On",
  "שריד": "Sarid",
  "שרשרת": "Sharsheret",
  "שתולה": "Shtula",
  "שתולים": "Shtulim",
  "תארבין": "Tirabin",
  "תאשור": "Ta'ashur",
  "תדהר": "Tidhar",
  "תובל": "Tuval",
  "תומר": "Tomer",
  "תחנת רכבת כפר ברוך": "Kfar Baruch Train Station",
  "תחנת רכבת כפר יהושוע": "Kfar Yehoshua Train Station",
  "תחנת רכבת קריית מלאכי - יואב": "Kiryat Mal'akhi-Yoav Train Station",
  "תחנת רכבת ראש העין": "Rosh Ha’Ayin Train Station",
  "תימורים": "Timorim",
  "תירוש": "Tirosh",
  "תל אביב - דרום העיר ויפו": "Tel Aviv - South And Jaffa",
  "תל אביב - מזרח": "Tel Aviv - East",
  "תל אביב - מרכז העיר": "Tel Aviv - City Center",
  "תל אביב - עבר הירקון": "Tel Aviv - Across The Yarkon",
  "תל חי": "Tel Hai",
  "תל יצחק": "Tel Itzhak",
  "תל מונד": "Tel Mond",
  "תל עדשים": "Tel Adashim",
  "תל ערד": "Tel Arad",
  "תל ציון": "Tel Zion",
  "תל קציר": "Tel Katzir",
  "תל שבע": "Tel Sheva",
  "תל תאומים": "Tel Teomim",
  "תלם": "Telem",
  "תלמי אליהו": "Talmei Eliyahu",
  "תלמי אלעזר": "Talmei Elazar",
  "תלמי יוסף": "Talmei Yossef",
  "תלמי יחיאל": "Talmei Yehiel",
  "תלמי יפה": "Talmei Yaffe",
  "תלמים": "Tlamim",
  "תמרת": "Timrat",
  "תנובות": "Tnuvot",
  "תעוז": "Taoz",
  "תעשיון צריפין": "Zrifin Industrial Zone",
  "תפרח": "Tifrach",
  "תקומה": "Tkuma",
  "תקוע": "Tko'a",
  "תקוע ד' וה'": "Tekoa Dalet And Hei",
  "תרום": "Tarom",
  "אשדוד -יא,יב,טו,יז,מרינה,סיט": "Ashdod - 11,12,15,17,Marina,City",
  "בני עי''ש": "Bnei Aish",
  "גבעת כ''ח": "Givat Koach",
  "דוב''ב": "Dovev",
  "יד רמב''ם": "Yad Rambam",
  "ייט''ב": "Yatev",
  "כפר ביל''ו": "Kfar Bilu",
  "כפר הרא''ה": "Kfar HaRoeh",
  "כפר הרי''ף": "Kfar HaRif",
  "כפר הרי''ף וצומת ראם": "Kfar HaRif & Tzommet Ram",
  "כפר חב''ד": "Kfar Chabad",
  "כפר מל''ל": "Kfar Malal",
  "כרם מהר''ל": "Kerem Maharal",
  "מצפה אבי''ב": "Mitzpe Aviv",
  "מרכז מיר''ב": "Merkaz Mirav",
  "ניר ח''ן": "Nir Chen",
  "נתיב הל''ה": "Netiv HaLamed Heh",
  "פעמי תש''ז": "Paamei Tashaz",
  "תלמי ביל''ו": "Talmei Bilu",
};

// Build reverse lookup (English lowercase → Hebrew)
const englishToHebrew: Record<string, string> = {};
for (const [he, en] of Object.entries(cityNames)) {
  englishToHebrew[en.toLowerCase()] = he;
}

export function getCityEnglishName(hebrewName: string): string {
  return cityNames[hebrewName] ?? hebrewName;
}

/**
 * Search cities by query in both Hebrew and English.
 * Returns matching Hebrew city names (the canonical form used by the API).
 */
export function searchCities(query: string, availableCities: string[]): string[] {
  const q = query.toLowerCase();
  return availableCities.filter((heCity) => {
    // Match Hebrew name
    if (heCity.includes(query)) return true;
    // Match English name
    const en = cityNames[heCity];
    if (en && en.toLowerCase().includes(q)) return true;
    return false;
  });
}

export default cityNames;
